# -*-python-*-

Import("env")

py_dir = '../vplants/treeeditor' if 'vplants' else '../treeeditor'

# Build wrappers as shared libraries
# First wrapper
env1 = env.Clone()

sources = env1.ALEAGlob('*.cpp')
target = "_treeeditor"
lib = ["treeeditor"]

env1.AppendUnique(LIBS=lib)
env1.ALEAWrapper(py_dir, target, sources)


